name: mobile
description: English Beater

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:


  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  csv: ^4.0.3
  cupertino_icons: ^0.1.2
  firebase_auth: 0.14.0+5
  google_sign_in: 4.0.7
  cloud_firestore: 0.12.9+5
  firebase_storage: 3.0.6
  shared_preferences: 0.5.3+4
  fluttertoast: 3.1.3
  flutter_tts: 0.6.0
  flutter_screenutil: 0.6.0
  flutter_facebook_login: ^3.0.0
  audioplayers: ^0.13.2
  speech_recognition: ^0.3.0
  cached_network_image: 1.1.3
  audioplayer: ^0.5.2
  intl: ^0.16.0
  provider: ^3.0.0
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/csvbook.json # import book and unit data to firebase
    # - assets/csv3.json # import conversation data to strapi
    # - assets/csvjson.json # import conversation data to firebase
    # - assets/input/ # import message to firebase
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/powered_by.png
    - assets/images/appname.png
    - assets/images/background_login.jpg

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf
