import 'package:mobile/core/models/Mess.dart';

final List<Mess> listMessages = [
  Mess(
      order: 0,
      text: "Hello, I’m Phonic Phil!",
      start: "3.452",
      end: "6.203",
      character: "Phil",
      type: TYPE.ONE_HUMAN),
  Mess(
      order: 1,
      text: "… and I’m Super Sue!",
      start: "6.686",
      end: "9.686",
      character: "Sue",
      type: TYPE.TWO_HUMAN),
  Mess(
      order: 2,
      text: "Grandmother, I’ve got a toothache.",
      start: "12.909",
      end: "16.953",
      character: "girl1",
      type: TYPE.ONE_HUMAN),
  Mess(
      order: 3,
      text: "And I’ve got a sore thumb",
      start: "17.866",
      end: "20.332",
      character: "boy",
      type: TYPE.TWO_HUMAN),
  Mess(
      order: 4,
      text: "Oh dear...",
      start: "21.154",
      end: "22.980",
      character: "ba",
      type: TYPE.ONE_HUMAN),
  Mess(
      order: 5,
      text: "Is it a plane?",
      start: "28.953",
      end: "30.580",
      character: "boy",
      type: TYPE.TWO_HUMAN),
  Mess(
      order: 6,
      text: "Is it a kite?",
      start: "31.347",
      end: "32.991",
      character: "girl1",
      type: TYPE.ONE_HUMAN),
  Mess(
      order: 7,
      text: "No It’s Phil and Sue!",
      start: "34.180",
      end: "37.500",
      character: "boy",
      type: TYPE.TWO_HUMAN),
  Mess(
      order: 8,
      text: "What’s the matter, Grandmother?",
      start: "45.928",
      end: "48.391",
      character: "Sue",
      type: TYPE.ONE_HUMAN),
  Mess(
      order: 9,
      text: "She has a toothache, and he has a sore thumb.",
      start: "49.214",
      end: "55.531",
      character: "ba",
      type: TYPE.TWO_HUMAN),
  Mess(
      order: 10,
      text: "Let’s go!",
      start: "62.147",
      end: "64.785",
      character: "Sue",
      type: TYPE.ONE_HUMAN),
  Mess(
      order: 11,
      text: "To the hospital!",
      start: "65.052",
      end: "65.052",
      character: "Phil",
      type: TYPE.TWO_HUMAN),
  Mess(
      order: 12,
      text: "Thank you, Phil and Sue!",
      start: "68.85",
      end: "72.080",
      character: "ba",
      type: TYPE.ONE_HUMAN),
];
